### ISSUE TITLE
Update documentation to specify which GHCs are available correctly

### ISSUE THREAD

**Issue by kozross** [haskell/actions#111]
<s>According to the docs, we only go up to `9.2.2`, but according to [this](https://www.haskell.org/ghc/blog/20220728-ghc-9.2.4-released.html) we already have `9.2.4`, and `9.2.3`'s been around [for two-ish months now](https://www.haskell.org/ghc/blog/20220527-ghc-9.2.3-released.html).</s>

The documentation states that the most recent GHC available is 9.2.2. However [this is not the case](https://github.com/haskell/actions/issues/111#issuecomment-1205151709). The documentation should be updated to be accurate.

**Comment by tfausak** [comment]
Both 9.2.3 and 9.2.4 work with this action. The documentation is unfortunately out of date.

**Comment by kozross** [comment]
@tfausak Modified the issue.

**Comment by TravisCardwell** [comment]
Based on the [haskell/actions/setup README][], my understanding is that the documentation (correctly) states which versions are pre-installed.  Other versions work if they are supported by GHCup, etc., but using them incurs additional cost, as the software has to be downloaded and installed on each job.

[haskell/actions/setup README]: <https://github.com/haskell/actions/tree/main/setup#haskellactionssetup>

Personally, I limit my jobs to versions that are pre-installed because I appreciate the *free* service and try to minimize the cost.  I am not sure if this is necessary, though, and I am eagerly waiting for GHC 9.2.4 installation.  Perhaps new releases are not pre-installed because the cost of downloading and installing the compiler on each job is not large?

**Comment by kozross** [comment]
@TravisCardwell I admit I missed that initial part, but the heading 'Version Support' doesn't really indicate this very well.

**Comment by Kleidukos** [comment]
The documentation should indeed be updated to better reflect what is available, in a way that prevents bitrot every couple of month.

**Comment by andreasabel** [comment]
Atm, the docs seem up-to-date.

Of course, it would be good to create the relevant section of the [`README`](https://github.com/haskell/actions/blob/main/setup/README.md) automatically from [`src/versions.json`](https://github.com/haskell/actions/blob/main/setup/src/versions.json).

PRs welcome!

**Comment by andreasabel** [comment]
@TravisCardwell wrote:
> Based on the [haskell/actions/setup README](https://github.com/haskell/actions/tree/main/setup?rgh-link-date=2022-08-04T20%3A32%3A42Z#haskellactionssetup), my understanding is that the documentation (correctly) states which versions are pre-installed. Other versions work if they are supported by GHCup, etc., but using them incurs additional cost, as the software has to be downloaded and installed on each job.
> 
> Personally, I limit my jobs to versions that are pre-installed because I appreciate the _free_ service and try to minimize the cost. I am not sure if this is necessary, though, and I am eagerly waiting for GHC 9.2.4 installation. Perhaps new releases are not pre-installed because the cost of downloading and installing the compiler on each job is not large?

Preinstalling versions of GHC is in the domain of the Github Action virtual environments.  This action does not know which versions are preinstalled, but if you request a versions of GHC that happens to be pre-installed, it will be activated rather than re-installed.

You can request any precise GHC version (even those not mentioned in the README) and the action will try to install it.
However, if you request an approximate GHC version such as 9.4, it will be resolved to the latest precise version the action is conscious about (atm 9.4.5).

Anyway, atm there is no pressing problem with this issue as the OP is fixed, so I am closing this issue as completed.
