### ISSUE TITLE
`stack-setup-ghc: false` treated as true

### ISSUE THREAD

**Issue by gelisam** [haskell/actions#22]
The documentation states that the default is `false`, but when the value is explicitly set to `false`, it is treated as if it was set to `true`.

[Here is an example run](https://github.com/gelisam/hawk/pull/243/checks?check_run_id=1628437184) in which `stack-setup-ghc` has been set to `false`; the logs show that `stack setup` is being called:

```
Run haskell/actions/setup@v1
  with:
    enable-stack: true
    stack-setup-ghc: false
    ghc-version: latest
    cabal-version: latest
    stack-version: latest
Preparing to setup a Haskell environment
Resolved latest to 8.10.2
Resolved latest to 3.2.0.0
Resolved latest to 2.5.1
Installing ghc version 8.10.2
Installing cabal version 3.2.0.0
Installing stack version 2.5.1
Pre-installing GHC with stack
  /opt/hostedtoolcache/stack/2.5.1/x64/stack setup 8.10.2
[...]
Setting up cabal
```

[Here is an example run](https://github.com/gelisam/hawk/pull/243/checks?check_run_id=1628462407) in which `stack-setup-ghc` was not specified; the logs show that `stack setup` is _not_ called, as expected:

```
Run haskell/actions/setup@v1
  with:
    enable-stack: true
    ghc-version: latest
    cabal-version: latest
    stack-version: latest
Preparing to setup a Haskell environment
Resolved latest to 8.10.2
Resolved latest to 3.2.0.0
Resolved latest to 2.5.1
Installing ghc version 8.10.2
Installing cabal version 3.2.0.0
Installing stack version 2.5.1
Setting up cabal
```

**Comment by jared-w** [comment]
Yeah, that's a bit of a wart in how this is all happening. I should make the docs clearer in that the booleans are really "set/not-set because it's a convention that other github actions follow and one that makes using yaml + strings + embedding values the least error prone.

The yaml values get serialized somewhere in the github actions runner and then turned into environment variables when they're loaded by the action code. So as far as the action is concerned, `stack-setup-ghc` is equivalent to exporting the env variable `STACK-SETUP-GHC`. The code also makes no distinction between missing and empty string. So missing/false/etc being equivalent to missing string is an assumption made by the toolkit very early on in the process.

**Comment by jared-w** [comment]
I've clarified the documentation just now to state that "boolean" configuration options are set/not-set semantics. I think that should hopefully prevent this from happening in the future. So I'm going to close this for now, if that's alright.

That said, set/unset is not always desirable, so I do have some code that I have written (and plan to eventually merge in) that will allow for (yaml) booleans to be used. When that happens, unset, set-to-empty-string, and any valid yaml 1.2 representation of `False` will be `false` (and documented thoroughly). Which... is terrible, but try not to think about that too hard :stuck_out_tongue_winking_eye:
