### ISSUE TITLE
Document that running `haskell/actions/setup` will overwrite `STACK_ROOT` variable on Windows

### ISSUE THREAD

**Issue by JordanMartinez** [haskell/actions#23]
While updating the PureScript compiler repo to migrate from Travis CI to GitHub Actions (see purescript/purescript#3980), we were setting `STACK_ROOT` to `$HOME/.stack` in one step and running this repo's setup action in a later step. Despite setting the variable, `stack path` always showed `stack-path: c:\sr` as the result.

After much exploration, I discovered that [`STACK_ROOT` is overwritten on Windows](https://github.com/haskell/actions/blob/main/setup/src/installer.ts#L25-L28). AFAIK, this isn't documented in this repo.

**Comment by hdgarrood** [comment]
Is it even necessary to overwrite STACK_ROOT? It's quite difficult to track down if your action is already explicitly setting STACK_ROOT elsewhere.

**Comment by jared-w** [comment]
Ah, that's certainly a case I should've thought about but missed initially, my apologies.

Stack root is set to c:\sr because that seems to be a recommended and commonly used one on windows, particularly to help get around path length restrictions. (Cabal's store also uses it in this repo by default for that reason)

Not documenting the variables is definitely an oversight, though.  I have the outputs documented already, and I'll go through and make sure the variables are documented as well.

That said, it's important (imo) to respect all explicitly set variables, which prevents confusion like this from happening, so I'll make sure to fix that. Thanks for opening an issue! I do apologise that the issue wasn't more easily identified.

**Comment by hdgarrood** [comment]
No worries at all! Thank you for your response.

**Comment by JordanMartinez** [comment]
I'm grateful that this action makes Haskell CI very easy.
