### ISSUE TITLE
Please, help us merge or integrate the HLint action

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell/actions#81]
In https://github.com/ndmitchell/hlint/issues/1311 we found & Neil blessed the currently best HLint action that exists.

An important feature of it - it allows softly suggesting code improvements, & so allows to use HLint in the project while also preserving the ease of pleasantness in the code merge processes.

How we would adopt the usage of it.

Calling author into the thread: @rwe.

**Comment by jared-w** [comment]
> How we would adopt the usage of it.

The long story short is that this repo was designed to be a "monorepo" of actions. So having a directory in the root called `hlint` that contains the hlint github action would be sufficient, and a PR that adds that would be accepted.

It shouldn't take too much modification to make https://github.com/rwe/actions-hlint-setup a directory in this repo if that's agreeable, and I can make @rwe a contributor to this repo so that they can continue to improve the action.

**Comment by andreasabel** [comment]
@hazelweakly 
> make @rwe a contributor to this repo so that they can continue to improve the action.

Hazel, could you please make me an admin of this repo so I can e.g. add @rwe as developer?  Thanks, that would help greatly.

**Comment by andreasabel** [comment]
Otherwise, there isn't anything left to do on this issue...
